apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: metrics-server
        args:
        - --cert-dir=/tmp
        - --secure-port=4443
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --requestheader-client-ca-file=/ca/front-proxy-ca.crt  # to verify cert
        - --tls-cert-file=/etc/kubernetes/pki/apiserver/tls.crt
        - --tls-private-key-file=/etc/kubernetes/pki/apiserver/tls.key
        - --kubelet-certificate-authority=/etc/kubernetes/pki/ca/ca.crt
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /ca
          name: ca-dir
      volumes:
      - emptyDir: {}
        name: tmp-dir
      - configMap:
          defaultMode: 420
          name: front-proxy-ca
        name: ca-dir
