apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: VnVzYWwgQWxpeWV2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  config: My configuration
---
apiVersion: v1
kind: Pod
metadata:
  name: projected-volume-test
  labels:
    volume: projected
spec:
  containers:
  - name: container-test
    image: busybox:1.28
    command: ["sleep", "3600"]
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: mysecret
          items:
            - key: username
              path: my-group/my-username
      - configMap:
          name: myconfig
          items:
            - key: config
              path: my-group/my-config
      - serviceAccountToken:
          audience: api
          expirationSeconds: 3600
          path: token
      - downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "cpu_limit"
              resourceFieldRef:
                containerName: container-test
                resource: limits.cpu
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
