apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-min-available
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: nginx
# ---
# apiVersion: policy/v1
# kind: PodDisruptionBudget
# metadata:
#   name: nginx-max-unavailable
# spec:
#   maxUnavailable: 2
#   selector:
#     matchLabels:
#       app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
