# RequestReceived - The stage for events generated as soon as the audit handler receives the request, and before it is delegated down the handler chain.
# ResponseStarted - Once the response headers are sent, but before the response body is sent. This stage is only generated for long-running requests (e.g. watch).
# ResponseComplete - The response body has been completed and no more bytes will be sent.
# Panic - Events generated when a panic occurred.

# None - don't log events that match this rule.
# Metadata - log events with metadata (requesting user, timestamp, resource, verb, etc.) but not request or response body.
# Request - log events with request metadata and body but not response body. This does not apply for non-resource requests.
# RequestResponse - log events with request metadata, request body and response body. This does not apply for non-resource requests.

# level: The audit level defining the verbosity of the event.
# resources: The object under audit (e.g., “ConfigMaps”).
# nonResourcesURL: A non resource Uniform Resource Locator (URL) path that is not associated with any resources.
# namespace: Specific objects within a namespace that are under audit.
# verb: Specific operation for audit – create, update, delete.
# users: Authenticated user that the rule applies to.
# userGroups: Authenticated user group the rule applies to.
# omitStages: Skips generating events on given stages.
---
apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "RequestReceived"
rules:
  # Log pod changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: ""
      # Resource "pods" doesn't match requests to any subresource of pods,
      # which is consistent with the RBAC policy.
      resources: ["pods"]

  # Log "pods/log", "pods/status" at Metadata level
  - level: Metadata  # None
    resources:
    - group: ""
      resources: ["pods/log", "pods/status"]

  # Don't log requests to a configmap called "controller-leader"
  - level: None
    resources:
    - group: ""
      resources: ["configmaps"]
      resourceNames: ["controller-leader"]

  # Don't log watch requests by the "system:kube-proxy" on endpoints or services
  - level: None
    users: ["system:kube-proxy"]
    verbs: ["watch"]
    resources:
    - group: "" # core API group
      resources: ["endpoints", "services"]

  # Log changes done by authenticated users
  - level: Request
    resources:
    - group: "" # core API group
      resources: ["*"]
    verbs: ["create", "update", "delete"]
    userGroups: ["system:authenticated"]

  # Don't log authenticated requests to certain non-resource URL paths.
  - level: None
    userGroups: ["system:authenticated"]
    nonResourceURLs:
    - "/api*" # Wildcard matching.
    - "/version"

  # Log the request body of configmap changes in kube-system.
  - level: Request
    resources:
    - group: "" # core API group
      resources: ["configmaps"]
    # This rule only applies to resources in the "kube-system" namespace.
    # The empty string "" can be used to select non-namespaced resources.
    namespaces: ["kube-system"]

  # Log secrets changes done by admins
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["secrets"]
    verbs: ["*"]
    userGroups: ["system:masters"]

  # Log configmap and secret changes in all other namespaces at the Metadata level.
  - level: Metadata
    resources:
    - group: "" # core API group
      resources: ["secrets", "configmaps"]

  # Log all other resources in core and extensions at the Request level.
  - level: Request
    resources:
    - group: "" # core API group
    - group: "extensions" # Version of group should NOT be included.

  # Log at Metadata level get/list
  - level: Metadata
    resources:
    - group: "" # core API group
      resources: ["*"]
    verbs: ["get", "list"]


  # A catch-all rule to log all other requests at the Metadata level.
  - level: Metadata
    # Long-running requests like watches that fall under this rule will not
    # generate an audit event in RequestReceived.
    omitStages:
      - "RequestReceived"

  # - level: Panic  # TODO: not working

  # Don't log remaning request/responses
  - level: None
