apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default
---
# creating secret not recommended
apiVersion: v1
kind: Secret
metadata:
  name: my-long-lived-secret
  annotations:
    kubernetes.io/service-account.name: my-service-account
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-service-account
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: sa-pod
spec:
  serviceAccount: my-service-account  # this will be deprecated
  serviceAccountName: my-service-account
  automountServiceAccountToken: true  # default: true
  containers:
  - name: my-container
    image: nginx:alpine
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: my-proj-vol
  volumes:
  - name: my-proj-vol
    projected:
      sources:
      - serviceAccountToken:
          path: my-proj-vol
          expirationSeconds: 600 #specify the desired epiration time in seconds
