---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-ebs-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi  # increase this to test resizing, pod need to restart to see changes
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ebs
  name: nginx-ebs
  namespace: default
spec:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ebs
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-ebs
  name: nginx-ebs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ebs
  template:
    metadata:
      labels:
        app: nginx-ebs
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-ebs
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /opt/data
      volumes:
      - name: nginx-persistent-storage
        persistentVolumeClaim:
          claimName: nginx-ebs-pv-claim
---
