# use below manifest after adding some data to mounted PV
# after adding data to pod wait some time to sync it to aws volumes, otherwise you can get empty result
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: ebs-csi-volume-snapshot-class
driver: ebs.csi.aws.com
deletionPolicy: Delete  # Retain
# parameters:
#   type: snap
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ebs-volume-snapshot
  namespace: default
spec:
  volumeSnapshotClassName: ebs-csi-volume-snapshot-class
  source:
    persistentVolumeClaimName: nginx-ebs-pv-claim
